name: gallery-api-local

services:
    nginx:
        image: nginx:latest
        volumes:
            -   ./:/var/www
            -   ./.docker/local/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - "8000:8000"
        container_name: app_nginx

        depends_on:
            - app
        networks:
            - gallery_api_network
    app:
        build:
            context: .
            dockerfile: .docker/local/Dockerfile
        volumes:
            -  ./:/var/www
        container_name: app_php
        env_file:
          - .env
        environment:
          - APP_KEY=${APP_KEY}
          - APP_NAME=${APP_NAME}
          - APP_ENV=${APP_ENV}
          - APP_URL=${APP_URL}
          - FRONTEND_URL=${FRONTEND_URL}
          - SESSION_DOMAIN=${SESSION_DOMAIN}
          - SANCTUM_STATEFUL_DOMAINS=${SANCTUM_STATEFUL_DOMAINS}
          - DB_CONNECTION=${DB_CONNECTION}
          - DB_HOST=${DB_HOST}
          - DB_PORT=${DB_PORT}
          - DB_DATABASE=${DB_DATABASE}
          - DB_USERNAME=${DB_USERNAME}
          - DB_PASSWORD=${DB_PASSWORD}
          - APP_DEBUG=${APP_DEBUG}
        depends_on:
            - db
        networks:
            - gallery_api_network
    db:
        image: mysql:8.0
        restart: always
        env_file:
            - .env
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        container_name: mysql
        networks:
            - gallery_api_network

networks:
    gallery_api_network:
        driver: bridge
volumes:
    mysql_data: {}
