name: Deploy Client Application

on:
  workflow_run:
    workflows:
      - "Build and Push Client Docker Images"
    types:
      - completed
  push:
    branches:
      - main
    paths:
      - '.github/workflows/client-deploy.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}  # Ваш приватный ключ

      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "./docker-compose.client.prod.yml"
          target: "$HOME"

      - name: Deploy and run migrations
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # Script for deploying the fullstack application

            export NODE_ENV=${{ secrets.ENV }}
            export VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}
            
           
            
            # Navigate to the deploy folder and initialize
            cd ~

            # Pull the latest images and start the containers
            docker-compose -f docker-compose.client.prod.yml pull
            docker-compose -f docker-compose.client.prod.yml up -d

            #
            echo "Deployment completed successfully!"
        env:
          ENV: ${{ secrets.ENV }}
          NODE_ENV: ${{ secrets.ENV }}
          VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
