on:
  push:
    branches:
      - main
  workflow_run:
    workflows: [ "Build and Push Fullstack Docker Images" ]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, gallery]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy and run migrations
        env:
          COMPOSE_PROJECT_NAME: ${{ vars.COMPOSE_PROJECT_NAME }}
          APP_ENV: ${{ secrets.ENV }}
          APP_DEBUG: false
          APP_NAME: ${{ secrets.APP_NAME }}
          APP_URL:  ${{ secrets.APP_URL }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          SESSION_DOMAIN: ${{ secrets.SESSION_DOMAIN }}
          SANCTUM_STATEFUL_DOMAINS: ${{ secrets.SANCTUM_STATEFUL_DOMAINS }}
          DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
          NODE_ENV: ${{ secrets.ENV }}
          VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
          APP_KEY: ${{ secrets.APP_KEY }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}



        run: |
          echo "COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}"

          docker-compose -f ./.deploy/docker-compose.yml pull
          docker-compose -f ./.deploy/docker-compose.yml down --volumes --remove-orphans || echo "No containers to remove"
          docker-compose -f ./.deploy/docker-compose.yml up -d

          echo "Waiting for MySQL to be ready..."
          until docker-compose exec db mysqladmin ping -h localhost -u root -p"${DB_PASSWORD}" --silent; do
          echo "Waiting for MySQL..."
          sleep 2
          done
          
          echo "MySQL is ready!"
          sleep 10

          docker-compose exec app php artisan migrate --force
          echo "Deployment completed successfully!"
