name: Deploy FullStack Application

on:
  workflow_run:
    workflows:
      - "Build and Push API Docker Images"  # Сборка и пуш API
      - "Build and Push Client Docker Images"  # Сборка и пуш клиентской части
    types:
      - completed
  push:
    branches:
      - main
    paths:
      - '.deploy/**'
      - '.github/workflows/deploy.yml**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Ваш приватный ключ

      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "./.deploy/docker-compose.yml"  # Путь к файлу на вашем репозитории
          target: "$HOME"  # Путь на сервере

      - name: Deploy and run migrations
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Script for deploying the fullstack application

            export COMPOSE_PROJECT_NAME=gallery
            export APP_ENV=${{ secrets.ENV }}
            export APP_DEBUG=false
            export APP_NAME=${{ secrets.APP_NAME }}
            export APP_URL=${{ secrets.APP_URL }}
            export FRONTEND_URL=${{ secrets.FRONTEND_URL }}
            export SESSION_DOMAIN=${{ secrets.SESSION_DOMAIN }}
            export SANCTUM_STATEFUL_DOMAINS=${{ secrets.SANCTUM_STATEFUL_DOMAINS }}
            export DB_CONNECTION=${{ secrets.DB_CONNECTION }}
            export NODE_ENV=${{ secrets.ENV }}
            export VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}
            export APP_KEY=${{ secrets.APP_KEY }}
            export DB_USERNAME=${{ secrets.MYSQL_USER }}
            export DB_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
            export DB_HOST=${{ secrets.MYSQL_SERVICE_NAME }}
            export DB_PORT=${{ secrets.MYSQL_PORT }}
            export DB_DATABASE=${{ secrets.MYSQL_DATABASE_GALLERY }}

            # Debug environment variables
            echo "APP_ENV: $APP_ENV"
            echo "APP_NAME: $APP_NAME"
            echo "MYSQL_DATABASE: $DB_DATABASE"
            
            # Navigate to the deploy folder and initialize
            cd ~

            # Pull the latest images and start the containers
            docker-compose pull
            docker-compose up -d

            # Running migrations
            docker-compose exec app php artisan migrate --force

            echo "Deployment completed successfully!"
        env:
          ENV: ${{ secrets.ENV }}
          APP_NAME: ${{ secrets.APP_NAME }}
          APP_URL: ${{ secrets.APP_URL }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          SESSION_DOMAIN: ${{ secrets.SESSION_DOMAIN }}
          SANCTUM_STATEFUL_DOMAINS: ${{ secrets.SANCTUM_STATEFUL_DOMAINS }}
          DB_CONNECTION: ${{ secrets.DB_CONNECTION }}
          NODE_ENV: ${{ secrets.ENV }}
          VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
          APP_KEY: ${{ secrets.APP_KEY }}
          DB_USERNAME: ${{ secrets.MYSQL_USER }}
          DB_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          DB_HOST: ${{ secrets.MYSQL_SERVICE_NAME }}
          DB_PORT: ${{ secrets.MYSQL_PORT }}
          DB_DATABASE: ${{ secrets.MYSQL_DATABASE_GALLERY }}
